server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  #############################新增网关配置###########################
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
            #- After=2022-06-29T16:28:44.483+08:00[Asia/Shanghai]  # 这个时间后才能起效
            #- Between=2022-06-29T15:28:44.483+08:00[Asia/Shanghai] ,2022-06-30T15:28:44.483+08:00[Asia/Shanghai]  # 两个时间点之间
            #- Cookie=chocolate, ch.p   # 该命令相当于发get请求，且没带cookiecurl http://localhost:9527/payment/lb   # 带cookie的curl http://localhost:9527/payment/lb --cookie "chocolate=chip"
            #- Header=X-Request-Id, \d+  #curl http://localhost:9527/payment/lb -H "X-Request-Id:123"
            #- Host=**.jxw.org,**.lsq.org   curl http://localhost:9527/payment/lb -H "Host:www.lsq.org"
            #- Method=GET,POST
            #- Query=username, \d+  #要有用户名还有就是值要是整数才能访问  curl http://localhost:9527/payment/lb?username=1
            #- RemoteAddr=192.168.0.1/24   #curl http://localhost:9527/payment/lb -H "RemoteAddr:192.168.0.10"

####################################################################

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka

